name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Cache npm modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .
        docker push ghcr.io/${{ github.repository }}:latest
      env:
        CR_PAT: ${{ secrets.GITHUB_TOKEN }}

    - name: Send failure email if workflow fails
      if: failure()
      run: |
        echo "Subject: GitHub Action Failure: ${{ github.repository }}" | sendmail -v -S smtp.gmail.com:587 -f ${{ secrets.MAIL_USERNAME }} -t ${{ secrets.MAIL_USERNAME }} -u "GitHub Action Failure" -m "The GitHub Action workflow has failed for the repository: ${{ github.repository }}."
      env:
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
